// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.9.0
// source: supply.proto

package protoc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SupplyListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *SupplyListRequest) Reset() {
	*x = SupplyListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_supply_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyListRequest) ProtoMessage() {}

func (x *SupplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyListRequest.ProtoReflect.Descriptor instead.
func (*SupplyListRequest) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{0}
}

func (x *SupplyListRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type SupplyCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SupplyCreateRequest) Reset() {
	*x = SupplyCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_supply_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyCreateRequest) ProtoMessage() {}

func (x *SupplyCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyCreateRequest.ProtoReflect.Descriptor instead.
func (*SupplyCreateRequest) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{1}
}

func (x *SupplyCreateRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SupplyCreateRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SupplyDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SupplyDeleteRequest) Reset() {
	*x = SupplyDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_supply_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyDeleteRequest) ProtoMessage() {}

func (x *SupplyDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyDeleteRequest.ProtoReflect.Descriptor instead.
func (*SupplyDeleteRequest) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{2}
}

func (x *SupplyDeleteRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SupplyDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SupplyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SupplyResponse) Reset() {
	*x = SupplyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_supply_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyResponse) ProtoMessage() {}

func (x *SupplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supply_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyResponse.ProtoReflect.Descriptor instead.
func (*SupplyResponse) Descriptor() ([]byte, []int) {
	return file_supply_proto_rawDescGZIP(), []int{3}
}

func (x *SupplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_supply_proto protoreflect.FileDescriptor

var file_supply_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x22, 0x29, 0x0a, 0x11, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x22, 0x3f, 0x0a, 0x13, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0x3b, 0x0a, 0x13, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2a, 0x0a, 0x0e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xdb, 0x01, 0x0a, 0x08,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x0a, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e,
	0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x53,
	0x75, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_supply_proto_rawDescOnce sync.Once
	file_supply_proto_rawDescData = file_supply_proto_rawDesc
)

func file_supply_proto_rawDescGZIP() []byte {
	file_supply_proto_rawDescOnce.Do(func() {
		file_supply_proto_rawDescData = protoimpl.X.CompressGZIP(file_supply_proto_rawDescData)
	})
	return file_supply_proto_rawDescData
}

var file_supply_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_supply_proto_goTypes = []interface{}{
	(*SupplyListRequest)(nil),   // 0: protoc.SupplyListRequest
	(*SupplyCreateRequest)(nil), // 1: protoc.SupplyCreateRequest
	(*SupplyDeleteRequest)(nil), // 2: protoc.SupplyDeleteRequest
	(*SupplyResponse)(nil),      // 3: protoc.SupplyResponse
}
var file_supply_proto_depIdxs = []int32{
	0, // 0: protoc.Supplies.SupplyList:input_type -> protoc.SupplyListRequest
	1, // 1: protoc.Supplies.SupplyCreate:input_type -> protoc.SupplyCreateRequest
	2, // 2: protoc.Supplies.SupplyDelete:input_type -> protoc.SupplyDeleteRequest
	3, // 3: protoc.Supplies.SupplyList:output_type -> protoc.SupplyResponse
	3, // 4: protoc.Supplies.SupplyCreate:output_type -> protoc.SupplyResponse
	3, // 5: protoc.Supplies.SupplyDelete:output_type -> protoc.SupplyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_supply_proto_init() }
func file_supply_proto_init() {
	if File_supply_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_supply_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_supply_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_supply_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_supply_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupplyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_supply_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_supply_proto_goTypes,
		DependencyIndexes: file_supply_proto_depIdxs,
		MessageInfos:      file_supply_proto_msgTypes,
	}.Build()
	File_supply_proto = out.File
	file_supply_proto_rawDesc = nil
	file_supply_proto_goTypes = nil
	file_supply_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SuppliesClient is the client API for Supplies service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SuppliesClient interface {
	SupplyList(ctx context.Context, in *SupplyListRequest, opts ...grpc.CallOption) (*SupplyResponse, error)
	SupplyCreate(ctx context.Context, in *SupplyCreateRequest, opts ...grpc.CallOption) (*SupplyResponse, error)
	SupplyDelete(ctx context.Context, in *SupplyDeleteRequest, opts ...grpc.CallOption) (*SupplyResponse, error)
}

type suppliesClient struct {
	cc grpc.ClientConnInterface
}

func NewSuppliesClient(cc grpc.ClientConnInterface) SuppliesClient {
	return &suppliesClient{cc}
}

func (c *suppliesClient) SupplyList(ctx context.Context, in *SupplyListRequest, opts ...grpc.CallOption) (*SupplyResponse, error) {
	out := new(SupplyResponse)
	err := c.cc.Invoke(ctx, "/protoc.Supplies/SupplyList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suppliesClient) SupplyCreate(ctx context.Context, in *SupplyCreateRequest, opts ...grpc.CallOption) (*SupplyResponse, error) {
	out := new(SupplyResponse)
	err := c.cc.Invoke(ctx, "/protoc.Supplies/SupplyCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *suppliesClient) SupplyDelete(ctx context.Context, in *SupplyDeleteRequest, opts ...grpc.CallOption) (*SupplyResponse, error) {
	out := new(SupplyResponse)
	err := c.cc.Invoke(ctx, "/protoc.Supplies/SupplyDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SuppliesServer is the server API for Supplies service.
type SuppliesServer interface {
	SupplyList(context.Context, *SupplyListRequest) (*SupplyResponse, error)
	SupplyCreate(context.Context, *SupplyCreateRequest) (*SupplyResponse, error)
	SupplyDelete(context.Context, *SupplyDeleteRequest) (*SupplyResponse, error)
}

// UnimplementedSuppliesServer can be embedded to have forward compatible implementations.
type UnimplementedSuppliesServer struct {
}

func (*UnimplementedSuppliesServer) SupplyList(context.Context, *SupplyListRequest) (*SupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplyList not implemented")
}
func (*UnimplementedSuppliesServer) SupplyCreate(context.Context, *SupplyCreateRequest) (*SupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplyCreate not implemented")
}
func (*UnimplementedSuppliesServer) SupplyDelete(context.Context, *SupplyDeleteRequest) (*SupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupplyDelete not implemented")
}

func RegisterSuppliesServer(s *grpc.Server, srv SuppliesServer) {
	s.RegisterService(&_Supplies_serviceDesc, srv)
}

func _Supplies_SupplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuppliesServer).SupplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Supplies/SupplyList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuppliesServer).SupplyList(ctx, req.(*SupplyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supplies_SupplyCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplyCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuppliesServer).SupplyCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Supplies/SupplyCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuppliesServer).SupplyCreate(ctx, req.(*SupplyCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supplies_SupplyDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupplyDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SuppliesServer).SupplyDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoc.Supplies/SupplyDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SuppliesServer).SupplyDelete(ctx, req.(*SupplyDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Supplies_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoc.Supplies",
	HandlerType: (*SuppliesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SupplyList",
			Handler:    _Supplies_SupplyList_Handler,
		},
		{
			MethodName: "SupplyCreate",
			Handler:    _Supplies_SupplyCreate_Handler,
		},
		{
			MethodName: "SupplyDelete",
			Handler:    _Supplies_SupplyDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supply.proto",
}
