openapi: "3.0.0"
info:
  version: 1.0.0
  title: wcafe
  description: wcafe store
servers:
  - url: http://{host}:{port}}/api/v1
    description: 開発用
    variables:
      host:
        default: localhost
      port:
        default: '8080'
paths:
# pathsオブジェクト
  /stores:
    get:
      summary: 店舗リスト
      tags:
        - stores
      parameters: []
      responses: #レスポンスを定義
        '200':
          description: 店舗の一覧表示
          content:
            application/json: # レスポンスの形式を指定
              schema:
                $ref: "#/components/schemas/stores"  #参照するモデル
    post:
      summary: 店舗の新規登録
      tags:
        - stores
      parameters: []
      requestBody: #リクエストボディ
          description: 店舗の新規登録
          content:
            application/json:
              schema: #POSTするオブジェクト
                type: object
                properties:
                  store:
                    $ref: "#/components/schemas/stores" 
      responses:
        '201':
          description: 新規登録に成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  store:
                    $ref: "#/components/schemas/stores"
  /pets:
    get:
      summary: 商品リスト
      tags:
        - pets
      parameters: []
      responses:
        '200':
          description: 商品一覧の表示
          content:
            application/json:
              schema:
                type: object
                properties:
                  pets:
                    type: array
                    items:
                     $ref: "#/components/schemas/pets"
  
  /pets/{pet_id}:
    get:
      summary: ID指定による商品取得
      description: 該当する商品を返す
      parameters: # リクエストパラメータ
        - name: pet_id
          in: path # パラメータをパス内に含める
          description: 商品ID
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: 商品情報
          content:
            application/json:
              schema: 
                type: object
                items:
                  $ref: '#/components/schemas/pets'
                example:
                  id: 65f79f22-73b8-11ea-bc55-0242ac130003
                  name: toy poodle
                  store_id: 75a68334-73b8-11ea-bc55-0242ac130003
  /users:
    get:
      tags:
        - users
      summary: ユーザ一覧取得
      description: ユーザ一覧取得
      parameters: []
      responses:
        '200':
          description: JSON配列の表示
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/users'
                example:
                  - id: UUID
                    number: 1
                    name: Sano
                  - id: UUID
                    number: 2
                    name: Suzuki

    post:
      tags:
       - users
      summary: ユーザ新規作成
      description: ユーザ新規作成
      parameters: []
      requestBody:
        description: user to create
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  $ref: "#/components/schemas/users"
            example:
              id: UUID
              number: 3
              name: Matsuno
      responses:
        '201':
          description: CREATED
  
components:
  schemas:
    stores:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: UUID
          readOnly: true
        name:
          type: string
        tag:
          type: string
          
    pets:
      type: object
      properties:
        id:
          description: 商品の識別子
          type: string
          format: UUID
          readOnly: true
        name:
          description: 商品名
          type: string
        store_id:
          description: 店の識別子
          type: string
          format: UUID
      required: 
        - id
        - name
        - store_i
        
    users:
      type: object
      properties:
        id:
          description: ユーザ識別子
          type: string
          format: UUID
          readOnly: true
        number:
          description: ユーザ番号
          type: integer
          format: int64
        name:
          description: ユーザ名
          type: string
      required:
        - id
        - number
        - name
