[db]
endpoint = "AMAZON_RDS_ENDPOINT"
user = "admin"
password = "DB_PASSWORD"
name = "wcafe"

[sqs]
region = "AWS_REGION"
pets_queue_url  = "PETS_SQS_QUEUE_URL"
stores_queue_url  = "STORES_SQS_QUEUE_URL"
users_queue_url = "USERS_SQS_QUEUE_URL"

[DynamoDB]
region = "DynamoDB_REGION"

[log]
file_path = "./log/"

[Conductor]
address = "CONDUCTOR_URL"
