[db]
endpoint = "AMAZON_RDS_ENDPOINT"
user = "admin"
password = "DB_PASSWORD"
name = "wcafe"

[sqs]
region = "AWS_REGION"
pets_queue_url  = "PETS_SQS_QUEUE_URL"
stores_queue_url  = "STORES_SQS_QUEUE_URL"
