openapi: 3.0.0
info:
  description: wcafe store
  title: wcafe
  version: 1.0.0
servers:
- url: /
paths:
  /stores:
    get:
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stores'
          description: 商品の一覧表示
      summary: 商品リスト
      tags:
      - stores
    post:
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                store:
                  $ref: '#/components/schemas/Stores'
              type: object
        description: 商品の新規登録
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
          description: 新規登録に成功
      summary: 商品の新規登録
      tags:
      - stores
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
  schemas:
    id:
      description: 店の識別子
      format: UUID
      readOnly: true
      type: string
    Stores:
      example:
        name: name
        id: id
        tag: tag
      properties:
        id:
          description: 店の識別子
          format: UUID
          readOnly: true
          type: string
        name:
          type: string
        tag:
          type: string
      required:
      - id
      - name
      type: object
    inline_object:
      properties:
        store:
          $ref: '#/components/schemas/Stores'
      type: object
    inline_response_201:
      example:
        store:
          name: name
          id: id
          tag: tag
      properties:
        store:
          $ref: '#/components/schemas/Stores'
