/*
 * wcafe
 *
 * wcafe store
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"
)


// StoresApiRouter defines the required methods for binding the api requests to a responses for the StoresApi
// The StoresApiRouter implementation should parse necessary information from the http request, 
// pass the data to a StoresApiServicer to perform the required actions, then write the service results to the http response.
type StoresApiRouter interface { 
	StoresGet(http.ResponseWriter, *http.Request)
	StoresPost(http.ResponseWriter, *http.Request)
}


// StoresApiServicer defines the api actions for the StoresApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type StoresApiServicer interface { 
	StoresGet() (interface{}, error)
	StoresPost(InlineObject) (interface{}, error)
}
