/*
 * wcafe
 *
 * wcafe store
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// StoresApiService is a service that implents the logic for the StoresApiServicer
// This service should implement the business logic for every endpoint for the StoresApi API. 
// Include any external packages or services that will be required by this service.
type StoresApiService struct {
}

// NewStoresApiService creates a default api service
func NewStoresApiService() StoresApiServicer {
	return &StoresApiService{}
}

// StoresGet - 商品リスト
func (s *StoresApiService) StoresGet() (interface{}, error) {
	return Stores{
		Id:   "IDIDIDID",
		Name: "example",
		Tag:  "Tag",
	}, nil
}

// StoresPost - 商品の新規登録
func (s *StoresApiService) StoresPost(inlineObject InlineObject) (interface{}, error) {
	// TODO - update StoresPost with the required logic for this service method.
	// Add api_stores_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'StoresPost' not implemented")
}
