/*
 * wcafe
 *
 * wcafe store
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
	//"github.com/gorilla/mux"
)

// A StoresApiController binds http requests to an api service and writes the service results to the http response
type StoresApiController struct {
	service StoresApiServicer
}

// NewStoresApiController creates a default api controller
func NewStoresApiController(s StoresApiServicer) Router {
	return &StoresApiController{service: s}
}

// Routes returns all of the api route for the StoresApiController
func (c *StoresApiController) Routes() Routes {
	return Routes{
		{
			"StoresGet",
			strings.ToUpper("Get"),
			"/stores",
			c.StoresGet,
		},
		{
			"StoresPost",
			strings.ToUpper("Post"),
			"/stores",
			c.StoresPost,
		},
	}
}

// StoresGet - 商品リスト
func (c *StoresApiController) StoresGet(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.StoresGet()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// StoresPost - 商品の新規登録
func (c *StoresApiController) StoresPost(w http.ResponseWriter, r *http.Request) {
	inlineObject := &InlineObject{}
	if err := json.NewDecoder(r.Body).Decode(&inlineObject); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.StoresPost(*inlineObject)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
