/*
 * wcafe
 *
 * wcafe store
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Stores struct {

	// 店の識別子
	Id string `json:"id"`

	Name string `json:"name"`

	Tag string `json:"tag,omitempty"`
}
