name: Docker_Test

on:
  push:
    branches: [docker-compose]
    # branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker_test:
    name: test 
    runs-on: ubuntu-latest
    steps:
        
    - name: checkout
      uses: actions/checkout@v2
      
    - name: build
      run: docker-compose build
      
    - name: run
      run: docker-compose up -d
    
    - name: Slack Notification
      # 前Stepの実行結果を判定
      # success() or failure() or always()
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: github-actions-result
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: ':fire::fire::fire:${{github.head_ref}}: ${{ job.status }}:fire::fire::fire:'
        SLACK_TITLE: Action Result （${{github.repository}}）
        SLACK_USERNAME: rtBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
